### ISSUE TITLE
How to produce .npy features file?

### ISSUE THREAD

**Issue by thelou1s** [jsalbert/sound_classification_ml_production#4]
Hi, I run you code well, But found that .npy is produced before and just download. So I want to know how to produce my .npy files? I run this "fe.compute_save_features", but only got .png feature files. How can I produce .npy like you did, thx!
![209992-5-4-17](https://user-images.githubusercontent.com/5654770/107134959-a9527700-6931-11eb-84f8-ecf8a2569c9f.png)

**Comment by jsalbert** [comment]
Hey @thelou1s,
Changed the part of the notebook that was saving the features:
```
@staticmethod
def save_features(audio_features, filepath):
    np.save(filepath, audio_features)
```

It should work now, let me know if there is any issue.
Thanks for using the repo!

**Comment by thelou1s** [comment]
Sorry for my late reply, as I was on vocation before. I will try your code, thank you!

BTW. Actually I saved npy by code below, and you can see I also reshaped features:

```
            # here save .npy feature as shape(39, 174, 1)
            npy_path = os.path.join(output_path, filepath.split('/')[-1].replace('wav', 'npy'))
            print('compute_save_features, npy_path = ' + str(npy_path))
            print('compute_save_features, audio_features.shape = ' + str(audio_features.shape))
            tmp_audio_features = audio_features.reshape(audio_features.shape[0], audio_features.shape[1], 1)
            print('compute_save_features, tmp_audio_features.shape = ' + str(tmp_audio_features.shape))
            np.save(npy_path, tmp_audio_features)
```

some logs like this:

```
compute_save_features, npy_path = /content/drive/MyDrive/dataset/sound_classification_ml_production/my_features_mfcc/162434-6-2-0.npy
compute_save_features, audio_features.shape = (39, 174)
compute_save_features, tmp_audio_features.shape = (39, 174, 1)
```

Is my code correct as well?
